#include "../include/NetworkFailure.exception.hpp"

NetworkFailure::NetworkFailure(std::string throwingFunction)
{
	_errorMsg = "Exception generated by " + throwingFunction;
}

NetworkFailure::~NetworkFailure() throw() {}

const char* NetworkFailure::what() const throw()
{
	return _errorMsg.c_str();
}
